graph LR
subgraph Виробництво
A(Машини) --> B(Дані про виробництво)
end

    subgraph Маркетинг
        C(Клієнти) -- email --> D(Дані про продаж)
    end

    subgraph Інженерія
        E(Дослідження) -- презентація --> F(Нові знання)
    end

    subgraph Інженерія знань
        B -- СУБД --> G{База знань}
        D -- СУБД --> G
        F -- СУБД --> G
        G -- звіт --> H(Прийняття рішень)
        H -- наказ --> A
        H -- план --> C
    end
